spring.application.name=Dalil_sante

# DATABASE CONFIGURATION

spring.datasource.url=jdbc:postgresql://localhost:5432/dalil_sante
spring.datasource.username=postgres
spring.datasource.password=C29010@?

# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER

server.port=8080

# ==========================
# JWT Configuration
# ==========================

jwt.secret=4B8F2E9C7A5D1F6E3A9B2C8D7F5E1A6C9B4D8F2A7E5C1D6B9A3F8E2C7D5A1B6
jwt.expiration=86400000